const tunes={cooleys:{title:"Cooley's Reel",type:'Reel',key:'E minor',meter:'4/4',tempo:108,aliases:"Joe Cooley's, Cooley's",story:"A modern session standard strongly associated with the great Irish button accordion player Joe Cooley. Its direct lift and memorable first bar make it an ideal TuneBase showcase tune.",sets:["The Wise Maid → Cooley's","The Silver Spear → Cooley's"],abc:`X:1\nT:Cooley's Reel\nM:4/4\nL:1/8\nR:reel\nQ:1/4=108\nK:Em\n|:D2|"Em"EBBA B2EB|"G"B2AB dBAG|"D"FDAD BDAD|"D"FDAD dAFD|\n"Em"EBBA B2EB|"G"B2AB defg|"D"afe^c dBAF|1 "Em"DEFD E2:|2 "Em"DEFD E4||`},saddle:{title:'Saddle the Pony',type:'Jig',key:'G major',meter:'6/8',tempo:96,aliases:"The Priest's Leap, Saddle the Pony Jig",story:"A bright, friendly jig heard in learning circles and lively sessions alike. Its strong rhythmic shape makes it the first TuneBase recognition demonstration.",sets:["Saddle the Pony → The Blarney Pilgrim","Saddle the Pony → Out on the Ocean"],abc:`X:2\nT:Saddle the Pony\nM:6/8\nL:1/8\nR:jig\nQ:3/8=96\nK:G\n|:"G"G3 GAB|"C"AGE "G"GED|"G"G3 GAB|"C"AGE "D"EDE|\n"G"G3 GAB|"C"AGE "G"GED|"G"G2B dBG|1 "D"AGE EDE:|2 "G"AGE G3||`},mug:{title:'Mug of Brown Ale',type:'Jig',key:'A major',meter:'6/8',tempo:98,aliases:'The Mug of Brown Ale, The Jug of Brown Ale',story:"A warm, rolling jig with the sociable character its title promises. It demonstrates alternative names and a second recognition result.",sets:["Mug of Brown Ale → The Cliffs of Moher","Mug of Brown Ale → The Kesh"],abc:`X:3\nT:Mug of Brown Ale\nM:6/8\nL:1/8\nR:jig\nQ:3/8=98\nK:A\n|:"A"A2E EFA|"D"B2A "E"Bcd|"A"A2E EFA|"E"BAG FED|\n"A"A2E EFA|"D"B2A "E"Bcd|"A"efe "E"dcB|1 "E"AFE E3:|2 "A"AFE A3||`}};
const app=document.getElementById('app');let metro=null,beat=0,drone=null,tuner={},catalog=[];
const demoCard=(id,role,copy,action)=>{const t=tunes[id];return `<article class='card demo-card'><span class='eyebrow'>${role}</span><h2>${t.title}</h2><p>${copy}</p><button class='primary' onclick="${action}">Open example</button></article>`};
async function loadCatalog(){try{const r=await fetch('tunes.json',{cache:'no-store'});const d=await r.json();catalog=d.tunes||[]}catch(e){catalog=[]}}
function go(x){scrollTo(0,0);
if(x==='home')app.innerHTML=`<section class='hero'><span class='eyebrow'>TUNEBASE VERSION 1</span><h1>Find it. Learn it.<br>Play it together.</h1><p>A growing Irish traditional tune library built for typed search, sound recognition, clear notation and instrument-by-instrument learning.</p><div class='row'><button class='primary' onclick="go('library')">Search the tune library</button><button class='secondary' onclick="go('find')">Recognise a tune</button></div><div class='catalog-stat'><b>250+ tune target</b><span>${catalog.length||206} seeded catalogue records currently included for database testing</span></div></section>
<section class='feature-grid'><article class='card'><span class='eyebrow'>LIBRARY</span><h2>Search every tune</h2><p>Find tunes by title, alternative title, type or key. Every completed record will use the same notes-and-chords template.</p></article><article class='card'><span class='eyebrow'>SOUND</span><h2>Play it to find it</h2><p>Record, whistle or upload a melody and return the closest catalogue matches.</p></article><article class='card'><span class='eyebrow'>LEARN</span><h2>Notes first, teaching below</h2><p>Full staff notation and chords remain central while fingering, looping and phrase practice sit in Learn Tune.</p></article></section>
<section class='demo-intro'><span class='eyebrow'>GUIDED TEST EXAMPLES</span><h2>Three examples, three different jobs</h2><p class='muted'>These are demonstrations only. They are not permanent featured tunes on the public homepage.</p><div class='grid'>${demoCard('cooleys','TUNE PAGE + LEARN TUNE','The agreed master template: main staff notes, chords, playback and instrument teaching.','showTune(\'cooleys\')')}${demoCard('saddle','SOUND RECOGNITION TEST','Run the recognition test and confirm it returns Saddle the Pony, then opens the full template.','go(\'find\')')}${demoCard('mug','DUPLICATE CHECK TEST','Check whether an incoming tune is already in TuneBase and open the existing record instead of creating a duplicate.','duplicateDemo()')}</div></section>`;
if(x==='library')renderLibrary();
if(x==='find')app.innerHTML=`<section class='page'><span class='eyebrow'>SOUND RECOGNITION TEST</span><h1>Find This Tune</h1><p>This Version 1 review uses Saddle the Pony as the single guided recognition example. Production recognition will compare a recording against the full indexed catalogue.</p></section><section class='card recognise'><div id='orb' class='orb'>◉</div><h2 id='rt'>Ready to listen</h2><p id='rc'>Press the test button to simulate a recording match.</p><div class='row' style='justify-content:center'><button class='primary' onclick="recognise('saddle')">Test Saddle the Pony recognition</button><button class='secondary' onclick="showTune('saddle')">View its tune template</button></div><div id='rr'></div></section>`;
if(x==='practice')practice();if(x==='sessions')sessions();if(x==='book')book();if(x==='add')add();}
function renderLibrary(query=''){const q=query.trim().toLowerCase();const rows=(catalog.length?catalog:[]).filter(t=>!q||[t['Canonical Title'],t['Alternative Titles'],t['Tune Type'],t['Key']].join(' ').toLowerCase().includes(q)).slice(0,60);app.innerHTML=`<section class='page'><span class='eyebrow'>GROWING CATALOGUE</span><h1>Tune Library</h1><p>${catalog.length||206} seeded tune records are included in this review database. The target is 250+ fully completed and sound-indexed tunes.</p><div class='library-search'><input id='libraryQuery' value="${query.replace(/"/g,'&quot;')}" placeholder='Search title, alternative title, type or key' oninput='renderLibrary(this.value)'><button class='primary' onclick='renderLibrary(libraryQuery.value)'>Search</button></div></section><div class='library-list'>${rows.length?rows.map(t=>`<article class='card library-row'><div><span class='eyebrow'>${t['Tune Type']||'TUNE'} · ${t['Time Signature']||'TIME TBC'}</span><h3>${t['Canonical Title']}</h3><p>${t['Alternative Titles']?`Also known as ${t['Alternative Titles']}`:'Alternative titles to be verified'}</p></div><span class='status-pill'>${t['Notation Status']||'Notation pending'}</span></article>`).join(''):`<section class='card'><h2>No matching tunes</h2><p>Try another title or spelling.</p></section>`}</div><section class='card examples-strip'><h2>Completed template examples</h2><p>Cooley's shows the full notes-and-learning template. Saddle the Pony demonstrates recognition. Mug of Brown Ale demonstrates duplicate checking.</p><div class='row'><button class='secondary' onclick="showTune('cooleys')">Cooley's template</button><button class='secondary' onclick="go('find')">Saddle recognition</button><button class='secondary' onclick='duplicateDemo()'>Mug duplicate check</button></div></section>`}
function duplicateDemo(){app.innerHTML=`<section class='page'><span class='eyebrow'>DUPLICATE CHECK TEST</span><h1>Is this tune already loaded?</h1><p>Mug of Brown Ale demonstrates the intake check that runs before a new tune can be added.</p></section><section class='card recognise'><div class='orb'>✓</div><h2>Existing tune found</h2><p><b>Mug of Brown Ale</b> is already in TuneBase. Alternative title checked: <b>The Jug of Brown Ale</b>.</p><div class='match-box'><span class='eyebrow'>MATCH CONFIDENCE · 98%</span><p>No new record will be created. The existing tune page is opened instead.</p></div><button class='primary' onclick="showTune('mug')">Open existing tune page</button><button class='secondary' onclick="go('add')">Test a tune not found</button></section>`}
function showTune(id){
  const t=tunes[id],saved=JSON.parse(localStorage.getItem('tbbook')||'[]');
  app.innerHTML=`<section class='page tunehead'><div><span class='eyebrow'>VERSION 1.0 TUNE PAGE</span><h1>${t.title}</h1><p>${t.type} · ${t.key} · ${t.meter} · ${t.tempo} BPM</p><p class='aliases'>Also known as: ${t.aliases}</p></div><button class='primary' onclick="toggleBook('${id}')">${saved.includes(id)?'Remove from':'Add to'} TuneBook</button></section>
  <section class='card music-card'>
    <div class='section-heading'><div><span class='eyebrow'>MAIN NOTES & CHORDS</span><h2>Full tune</h2><p class='muted'>Staff notation is the main view. Guitar chords sit above the bars and stay linked to playback.</p></div><div class='tempo-box'><label for='tempo'>Tempo <b id='tempoValue'>${t.tempo}</b> BPM</label><input id='tempo' type='range' min='45' max='180' value='${t.tempo}'></div></div>
    <div class='main-note-label'><b>Main notes and chords</b><small>The full staff stays visible while Learn Tune adds fingering below.</small></div><div class='chord-key'><span>G</span><span>C</span><span>D</span><span>Em</span></div><div id='paper' class='notation-paper'></div>
    <div class='transport'><button class='primary' id='play'>▶ Play</button><button class='secondary' id='pause'>Ⅱ Pause</button><button class='secondary' id='stop'>■ Stop</button><button class='secondary' id='loopA'>Loop A</button><button class='secondary' id='loopB'>Loop B</button></div>
    <div class='progress-track'><span id='progressFill'></span></div>
  </section>
  <div class='two tune-layout'><div class='stack'>
    <section class='card learn-card'><div class='section-heading'><div><span class='eyebrow'>LEARN TUNE</span><h2>Teach me this tune</h2><p class='muted'>Choose an instrument, slow the tune down and work phrase by phrase while keeping the main notes visible above.</p></div></div>
      <div class='learn-tabs'><button class='chip active' onclick="showLearning('fiddle',this)">Fiddle</button><button class='chip' onclick="showLearning('accordion',this)">Accordion</button><button class='chip' onclick="showLearning('whistle',this)">Whistle</button><button class='chip' onclick="showLearning('guitar',this)">Guitar</button></div>
      <div id='learningPanel'></div>
      <div class='practice-options'><label><input type='checkbox' checked> Highlight notes during playback</label><label><input type='checkbox'> Show note names under staff</label><label><input type='checkbox'> Count in before playing</label></div>
      <div class='phrase-grid'><button class='secondary'>Play A1 slowly</button><button class='secondary'>Repeat A2</button><button class='secondary'>Play B1 slowly</button><button class='secondary'>Repeat B2</button></div>
    </section>
    <section class='card'><span class='eyebrow'>STORY & HISTORY</span><h2>${t.title}</h2><p>${t.story}</p></section>
    <details class='card abc-details'><summary><b>ABC source</b> <span class='muted'>for advanced users</span></summary><pre>${t.abc}</pre></details>
  </div><aside class='stack'>
    <section class='card'><span class='eyebrow'>TUNE DETAILS</span><p><b>Type:</b> ${t.type}</p><p><b>Key:</b> ${t.key}</p><p><b>Time:</b> ${t.meter}</p><p><b>Alternative names:</b> ${t.aliases}</p></section>
    <section class='card'><span class='eyebrow'>COMMON SETS</span>${t.sets.map(s=>`<p><b>${s}</b></p>`).join('')}</section>
    <section class='card'><span class='eyebrow'>PAGE TOOLS</span><div class='side-actions'><button class='secondary'>Print notes</button><button class='secondary'>Download PDF</button><button class='secondary'>Share tune</button><button class='secondary'>Report correction</button></div></section>
  </aside></div>`;
  showLearning('fiddle');
  try{
    const visual=ABCJS.renderAbc('paper',t.abc,{responsive:'resize',add_classes:true,staffwidth:900,scale:1.05})[0];
    const synth=new ABCJS.synth.CreateSynth();
    const controller=new ABCJS.synth.SynthController();
    controller.load('#paper',null,{displayLoop:false,displayRestart:false,displayPlay:false,displayProgress:false});
    synth.init({visualObj:visual}).then(()=>controller.setTune(visual,false,{qpm:t.tempo}));
    play.onclick=()=>controller.play();
    pause.onclick=()=>controller.pause();
    stop.onclick=()=>controller.restart();
    tempo.oninput=async()=>{tempoValue.textContent=tempo.value;controller.restart();await controller.setTune(visual,false,{qpm:+tempo.value})};
    loopA.onclick=()=>{alert('A-part looping is shown in the Version 1 layout and will be connected to exact bar ranges in the production player.')};
    loopB.onclick=()=>{alert('B-part looping is shown in the Version 1 layout and will be connected to exact bar ranges in the production player.')};
  }catch(e){paper.innerHTML='<p>Notation requires an internet connection on first load.</p>'}
}
function showLearning(kind,button){
  document.querySelectorAll('.learn-tabs .chip').forEach(x=>x.classList.remove('active'));if(button)button.classList.add('active');
  const views={
    fiddle:`<div class='learning-view'><div class='instrument-icon'>🎻</div><div><h3>Fiddle fingering</h3><p>Finger numbers appear beneath the notes: <b>0</b> open string, then <b>1–3</b>. Bowing and string changes can be added without cluttering the main score.</p><div class='finger-strip'><span>G · 0</span><span>A · 1</span><span>B · 2</span><span>D · 0</span><span>E · 1</span></div></div></div>`,
    accordion:`<div class='learning-view'><div class='instrument-icon'>🪗</div><div><h3>Button accordion fingering</h3><p>Select B/C or C♯/D. The teaching layer will show button number, row and bellows direction for each phrase.</p><div class='finger-strip'><span>4 outer · push</span><span>5 inner · draw</span><span>6 outer · draw</span></div></div></div>`,
    whistle:`<div class='learning-view'><div class='instrument-icon'>🪈</div><div><h3>Tin whistle fingering</h3><p>Hole diagrams follow the highlighted note, with ornament suggestions kept optional for beginners.</p><div class='whistle-holes'><i></i><i></i><i class='open'></i><i></i><i class='open'></i><i class='open'></i></div></div></div>`,
    guitar:`<div class='learning-view'><div class='instrument-icon'>🎸</div><div><h3>Guitar accompaniment</h3><p>Chord names already appear above the main staff. This teaching view adds shapes, suggested changes and a simple backing pattern.</p><div class='chord-shapes'><span><b>Em</b><small>022000</small></span><span><b>G</b><small>320003</small></span><span><b>D</b><small>xx0232</small></span></div></div></div>`
  };learningPanel.innerHTML=views[kind]||views.fiddle;
}
function toggleBook(id){let s=JSON.parse(localStorage.getItem('tbbook')||'[]');s=s.includes(id)?s.filter(x=>x!==id):[...s,id];localStorage.setItem('tbbook',JSON.stringify(s));showTune(id)}
function recognise(id){orb.classList.add('pulse');rt.textContent='Listening…';rc.textContent='Analysing pitch contour, rhythm and melodic fingerprint.';rr.innerHTML='';setTimeout(()=>{orb.classList.remove('pulse');rt.textContent='Match found';const t=tunes[id];rr.innerHTML=`<div class='card' style='margin-top:22px;text-align:left'><span class='eyebrow'>TOP MATCH · 98%</span><h2>${t.title}</h2><p>${t.type} · ${t.key}</p><button class='primary' onclick="showTune('${id}')">Open tune</button><p><b>Other possible matches</b><br>The Blarney Pilgrim — 54%<br>Out on the Ocean — 37%</p></div>`},2200)}
function practice(){app.innerHTML=`<section class='page'><span class='eyebrow'>PRACTICE TOOLS</span><h1>Tune up and settle in</h1></section><div class='row'><button class='chip' onclick="tool('tuner')">Tuner</button><button class='chip' onclick="tool('metro')">Metronome</button><button class='chip' onclick="tool('drone')">Drone</button></div><div id='tool'></div>`;tool('tuner')}
function tool(x){if(x==='tuner')tool.innerHTML=`<section class='card tool'><span class='eyebrow'>CHROMATIC · FIDDLE G–D–A–E · WHISTLE D</span><div id='note' class='big'>—</div><p id='cents'>Tap start and play one steady note</p><div class='needlebox'><div id='needle' class='needle'></div></div><button class='primary' onclick='startTuner()'>Start microphone tuner</button><p class='muted'>Audio is analysed only in your browser.</p></section>`;if(x==='metro')tool.innerHTML=`<section class='card tool'><div id='bpm' class='big'>100</div><p>BPM</p><input id='slider' type='range' min='40' max='220' value='100' oninput='bpm.textContent=this.value'><div class='lights'><i></i><i></i><i></i><i></i></div><button class='primary' onclick='toggleMetro(this)'>Start</button></section>`;if(x==='drone')tool.innerHTML=`<section class='card tool'><h2>Drone notes</h2><p>Hold a steady tonal centre while practising intonation.</p><div class='drone'><button onclick="startDrone(196,this)">G</button><button onclick="startDrone(146.83,this)">D</button><button onclick="startDrone(220,this)">A</button><button onclick="startDrone(164.81,this)">E</button></div><button class='secondary' onclick='stopDrone()'>Stop drone</button></section>`}
function toggleMetro(b){if(metro){clearInterval(metro);metro=null;b.textContent='Start';document.querySelectorAll('.lights i').forEach(x=>x.className='');return}const tick=()=>{let l=[...document.querySelectorAll('.lights i')];l.forEach((x,i)=>x.className=i===beat?'on':'');let c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=beat?700:1000;g.gain.setValueAtTime(.15,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.06);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.07);beat=(beat+1)%4};tick();metro=setInterval(tick,60000/+slider.value);b.textContent='Stop'}
function startDrone(f,b){stopDrone();let c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.value=.13;o.connect(g).connect(c.destination);o.start();drone={c,o};document.querySelectorAll('.drone button').forEach(x=>x.className='');b.className='on'}function stopDrone(){if(drone){drone.o.stop();drone.c.close();drone=null}document.querySelectorAll('.drone button').forEach(x=>x.className='')}
async function startTuner(){try{let stream=await navigator.mediaDevices.getUserMedia({audio:true}),c=new AudioContext(),a=c.createAnalyser();a.fftSize=2048;c.createMediaStreamSource(stream).connect(a);let buf=new Float32Array(a.fftSize);function loop(){a.getFloatTimeDomainData(buf);let r=0;for(let v of buf)r+=v*v;if(Math.sqrt(r/buf.length)>.01){let best=0,off=0;for(let o=20;o<700;o++){let s=0;for(let i=0;i<buf.length-o;i++)s+=buf[i]*buf[i+o];if(s>best){best=s;off=o}}let f=c.sampleRate/off,n=Math.round(12*Math.log2(f/440)+69),names=['C','C♯','D','E♭','E','F','F♯','G','A♭','A','B♭','B'],target=440*Math.pow(2,(n-69)/12),ct=1200*Math.log2(f/target);note.textContent=names[(n%12+12)%12];cents.textContent=`${Math.round(ct)} cents · ${f.toFixed(1)} Hz`;needle.style.transform=`rotate(${Math.max(-45,Math.min(45,ct))}deg)`}requestAnimationFrame(loop)}loop()}catch(e){alert('Microphone permission is required.')}}
function sessions(){app.innerHTML=`<section class='page'><span class='eyebrow'>PLAY TOGETHER</span><h1>Sessions</h1><p>Review demonstration of the future live directory.</p></section><div class='row'><button class='chip' onclick="map.classList.remove('heatmode')">Session map</button><button class='chip' onclick="map.classList.add('heatmode')">Heat map</button></div><section class='card'><div id='map' class='map'><button class='pin p1'>♪</button><button class='pin p2'>♪</button><button class='pin p3'>♪</button><div class='heat h1'></div><div class='heat h2'></div></div></section><div class='grid'><section class='card'><h3>Kennelly's Session</h3><b>Cork City · Thursday 9 pm</b><p>Established local repertoire.</p></section><section class='card'><h3>Foley's Draft Session</h3><b>Dublin · Tuesday 8:30 pm</b><p>Version 0.8 review listing.</p></section><section class='card'><h3>The Crane Bar</h3><b>Galway · Nightly programme</b><p>Example future venue card.</p></section></div>`}
function book(){let s=JSON.parse(localStorage.getItem('tbbook')||'[]');app.innerHTML=`<section class='page'><span class='eyebrow'>PERSONAL COLLECTION</span><h1>My TuneBook</h1><p>Saved on this device.</p></section><div class='grid'>${s.length?s.map(id=>{let t=tunes[id];return `<article class='card'><h2>${t.title}</h2><p>${t.type} · ${t.key}</p><button class='primary' onclick="showTune('${id}')">Open</button></article>`}).join(''):`<section class='card'><h2>Your TuneBook is empty</h2><button class='primary' onclick="go('library')">Browse tunes</button></section>`}</div>`}
function add(){app.innerHTML=`<section class='page'><span class='eyebrow'>CONTRIBUTE</span><h1>Add a tune</h1><p>No ABC entry required.</p></section><div class='grid'><button class='card' onclick="alert('Version 1.0 will recognise the recording first, then create an editor-review draft.')"><h2>🎙 Record a tune</h2><p>Capture the melody and check known tunes.</p></button><button class='card' onclick="alert('Version 1.0 will search titles and alternative names before creating a draft.')"><h2>⌨ Type its name</h2><p>Search before proposing a new tune.</p></button></div>`}
if('serviceWorker' in navigator){navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister()));} if('caches' in window){caches.keys().then(keys=>keys.forEach(k=>caches.delete(k)));} showTune('saddle');
